module.exports = [
  {
    ignores: [
      "node_modules/**",
      "browser-polyfill.js",
      "coverage/**",
      "generate-icons.js",
      "test-import.js",
      "eslint.config.js",
      "test-api-key.js"
    ]
  },
  {
    files: ["**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        chrome: "readonly",
        browser: "readonly",
        console: "readonly",
        document: "readonly",
        window: "readonly",
        fetch: "readonly",
        URL: "readonly",
        URLSearchParams: "readonly",
        btoa: "readonly",
        atob: "readonly",
        performance: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        MutationObserver: "readonly",
        Date: "readonly",
        Math: "readonly",
        String: "readonly",
        Object: "readonly",
        Array: "readonly",
        Promise: "readonly",
        Error: "readonly",
        importScripts: "readonly",
        ApiService: "readonly",
        DnrService: "readonly",
        AD_NETWORK_DOMAINS: "readonly",
        AD_BLOCK_RESOURCE_TYPES: "readonly",
        stopStrikeInjector: "readonly",
        initStrikeInjector: "readonly",
        getAdSize: "readonly",
        renderStrikeCard: "readonly",
        findAdElements: "readonly",
        observeNewAds: "readonly",
        sessionStorage: "readonly",
        history: "readonly",
        module: "readonly",
        exports: "readonly",
        require: "readonly",
        process: "readonly",
        __dirname: "readonly"
      }
    },
    rules: {
      "no-console": "off",
      "no-debugger": "warn",
      "no-unused-vars": ["error", { "argsIgnorePattern": "^_.*$", "varsIgnorePattern": "^_.*$", "caughtErrorsIgnorePattern": "^_.*$" }],
      "no-undef": "error",
      "no-useless-escape": "warn"
    }
  },
  {
    files: ["tests/**/*.js"],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: "script",
      globals: {
        chrome: "readonly",
        browser: "readonly",
        console: "readonly",
        document: "readonly",
        window: "readonly",
        fetch: "readonly",
        URL: "readonly",
        btoa: "readonly",
        atob: "readonly",
        performance: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        MutationObserver: "readonly",
        Date: "readonly",
        Math: "readonly",
        String: "readonly",
        Object: "readonly",
        Array: "readonly",
        Promise: "readonly",
        Error: "readonly",
        importScripts: "readonly",
        ApiService: "readonly",
        sessionStorage: "readonly",
        history: "readonly",
        module: "readonly",
        exports: "readonly",
        require: "readonly",
        process: "readonly",
        __dirname: "readonly",
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        beforeEach: "readonly",
        afterEach: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        expect: "readonly",
        jest: "readonly",
        global: "readonly",
        matchUrlToAction: "readonly"
      }
    },
    rules: {
      "no-console": "off",
      "no-debugger": "off",
      "no-unused-vars": "off",
      "no-undef": "warn",
      "no-useless-escape": "warn"
    }
  }
];
